---
all:
  children:
    nuc:
      hosts:
        cei-nuc-01:
          ansible_host: "{{ vault_nuc_ansible_host }}"
          ansible_user: "{{ vault_nuc_ansible_user }}"
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: "{{ vault_nuc_ssh_private_key_file }}"
