"""Relate coursor to datasource

Revision ID: b663d6899995
Revises: 11ad96dfca59
Create Date: 2026-03-06 15:06:27.131712+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b663d6899995'
down_revision: Union[str, None] = '11ad96dfca59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_fetch_cursor', sa.Column('datasource_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_api_cursor_connector_endpoint_device'), 'api_fetch_cursor', type_='unique')
    op.drop_index(op.f('idx_api_cursor_lookup'), table_name='api_fetch_cursor')
    op.create_index('idx_api_cursor_lookup', 'api_fetch_cursor', ['connector_id', 'endpoint_id', 'datasource_id'], unique=False)
    op.create_foreign_key(None, 'api_fetch_cursor', 'datasource', ['datasource_id'], ['id'])
    op.drop_column('api_fetch_cursor', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_fetch_cursor', sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_fetch_cursor', type_='foreignkey')
    op.drop_index('idx_api_cursor_lookup', table_name='api_fetch_cursor')
    op.create_index(op.f('idx_api_cursor_lookup'), 'api_fetch_cursor', ['connector_id', 'endpoint_id', 'device_id'], unique=False)
    op.create_unique_constraint(op.f('uq_api_cursor_connector_endpoint_device'), 'api_fetch_cursor', ['connector_id', 'endpoint_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_fetch_cursor', 'datasource_id')
    # ### end Alembic commands ###
