"""Polish models

Revision ID: 11ad96dfca59
Revises: 001_initial
Create Date: 2026-03-06 14:15:50.742511+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ad96dfca59'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dairy_production', 'ingestion_method')
    op.drop_index(op.f('idx_datasource_category'), table_name='datasource')
    op.drop_index(op.f('idx_datasource_client'), table_name='datasource')
    op.drop_index(op.f('idx_datasource_data_type'), table_name='datasource')
    op.drop_index(op.f('idx_datasource_status'), table_name='datasource')
    op.drop_column('environmental_metrics', 'ingestion_method')
    op.drop_index(op.f('idx_energy_daily_datasource_ts'), table_name='fact_energy_daily')
    op.drop_constraint(op.f('uq_energy_daily_datasource_ts'), 'fact_energy_daily', type_='unique')
    op.drop_constraint(op.f('fact_energy_daily_datasource_id_fkey'), 'fact_energy_daily', type_='foreignkey')
    op.drop_column('fact_energy_daily', 'ingestion_method')
    op.drop_column('fact_energy_daily', 'datasource_id')
    op.drop_index(op.f('idx_energy_hourly_datasource_ts'), table_name='fact_energy_hourly')
    op.drop_constraint(op.f('uq_energy_hourly_datasource_ts'), 'fact_energy_hourly', type_='unique')
    op.drop_constraint(op.f('fact_energy_hourly_datasource_id_fkey'), 'fact_energy_hourly', type_='foreignkey')
    op.drop_column('fact_energy_hourly', 'ingestion_method')
    op.drop_column('fact_energy_hourly', 'datasource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_energy_hourly', sa.Column('datasource_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fact_energy_hourly', sa.Column('ingestion_method', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fact_energy_hourly_datasource_id_fkey'), 'fact_energy_hourly', 'datasource', ['datasource_id'], ['id'])
    op.create_unique_constraint(op.f('uq_energy_hourly_datasource_ts'), 'fact_energy_hourly', ['datasource_id', 'ts'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_energy_hourly_datasource_ts'), 'fact_energy_hourly', ['datasource_id', 'ts'], unique=False)
    op.add_column('fact_energy_daily', sa.Column('datasource_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fact_energy_daily', sa.Column('ingestion_method', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fact_energy_daily_datasource_id_fkey'), 'fact_energy_daily', 'datasource', ['datasource_id'], ['id'])
    op.create_unique_constraint(op.f('uq_energy_daily_datasource_ts'), 'fact_energy_daily', ['datasource_id', 'ts'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_energy_daily_datasource_ts'), 'fact_energy_daily', ['datasource_id', 'ts'], unique=False)
    op.add_column('environmental_metrics', sa.Column('ingestion_method', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_datasource_status'), 'datasource', ['status'], unique=False)
    op.create_index(op.f('idx_datasource_data_type'), 'datasource', ['data_type'], unique=False)
    op.create_index(op.f('idx_datasource_client'), 'datasource', ['client'], unique=False)
    op.create_index(op.f('idx_datasource_category'), 'datasource', ['source_category'], unique=False)
    op.add_column('dairy_production', sa.Column('ingestion_method', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
