"""Relate coursor to datasource

Revision ID: ad5ec9320389
Revises: 11ad96dfca59
Create Date: 2026-03-13 13:21:08.073191+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5ec9320389'
down_revision: Union[str, None] = '11ad96dfca59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_fetch_cursor', sa.Column('datasource_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_api_cursor_connector_endpoint_device'), 'api_fetch_cursor', type_='unique')
    op.drop_index(op.f('idx_api_cursor_lookup'), table_name='api_fetch_cursor')
    op.create_index('idx_api_cursor_lookup', 'api_fetch_cursor', ['connector_id', 'endpoint_id', 'datasource_id'], unique=False)
    op.create_unique_constraint('uq_api_cursor_connector_endpoint_datasource', 'api_fetch_cursor', ['connector_id', 'endpoint_id', 'datasource_id'])
    op.create_foreign_key('fk_api_fetch_cursor_datasource', 'api_fetch_cursor', 'datasource', ['datasource_id'], ['id'])
    op.drop_column('api_fetch_cursor', 'device_id')
    op.create_unique_constraint('fact_energy_daily_ts_key', 'fact_energy_daily', ['ts'])
    op.create_unique_constraint('fact_energy_hourly_ts_key', 'fact_energy_hourly', ['ts'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fact_energy_hourly_ts_key', 'fact_energy_hourly', type_='unique')
    op.drop_constraint('fact_energy_daily_ts_key', 'fact_energy_daily', type_='unique')
    op.add_column('api_fetch_cursor', sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_api_fetch_cursor_datasource', 'api_fetch_cursor', type_='foreignkey')
    op.drop_constraint('uq_api_cursor_connector_endpoint_datasource', 'api_fetch_cursor', type_='unique')
    op.drop_index('idx_api_cursor_lookup', table_name='api_fetch_cursor')
    op.create_index(op.f('idx_api_cursor_lookup'), 'api_fetch_cursor', ['connector_id', 'endpoint_id', 'device_id'], unique=False)
    op.create_unique_constraint(op.f('uq_api_cursor_connector_endpoint_device'), 'api_fetch_cursor', ['connector_id', 'endpoint_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_fetch_cursor', 'datasource_id')
    # ### end Alembic commands ###
