{
 "title": "Milk production, energy consumption, and environmental metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site_name",
    "label": "Lefkos Kallenos farm",
    "query": "select client from generic_device"
   }
  ]
 },
 "panels": [
  {
   "title": "Cumulative Heat Load (Daily Hours of Heat Stress)",
   "type": "barchart",
   "description": "This tracks how many hours per day the animals spend above THI 68\n\nLivestock can handle a high THI during the day if it drops at night, but if the night-time THI stays above 68, they cannot recover, and that is when production crashes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "ocei3",
     "rawSql": "WITH hourly_thi AS (\n    SELECT \n        date_trunc('hour', \"timestamp\") AS hr,\n        -- Using the NRC Livestock Formula\n        AVG((1.8 * temperature + 32) - ((0.55 - 0.0055 * humidity) * (1.8 * temperature - 26))) AS avg_thi\n    FROM environmental_metrics as env\n    JOIN generic_device as d ON d.id = CAST(env.source_device_id AS INT)\n    WHERE \n        $__timeFilter(\"timestamp\") \n        -- Equality filter for the dashboard variable\n        AND d.client = '$site_name' \n    GROUP BY 1, d.client\n)\nSELECT \n    date_trunc('day', hr) AS \"time\",\n    COUNT(*) FILTER (WHERE avg_thi < 65) AS \"Recovery Hours (Optimal)\",\n    COUNT(*) FILTER (WHERE avg_thi >= 68) AS \"Stress Hours (THI > 68)\",\n    COUNT(*) FILTER (WHERE avg_thi >= 72) AS \"Danger Hours (THI > 72)\"\nFROM hourly_thi\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Device",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "ocei3",
     "rawSql": "SELECT alias, client, device_id FROM generic_device LIMIT 50 "
    }
   ]
  },
  {
   "title": "(agg) Daily milk production (kg) vs energy consumption (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "ocei",
     "rawSql": "SELECT\n  production_date AS \"time\",\n  (day_production_per_cow_kg * number_of_animals) AS \"Total Milk Production (kg)\"\nFROM dairy_production as prod\nJOIN generic_device as d ON d.id = CAST(prod.source_device_id AS INT)\nWHERE $__timeFilter(production_date) and d.client = '$site_name'\nORDER BY 1;"
    },
    {
     "dataset": "ocei",
     "rawSql": "SELECT\n  DATE_TRUNC('day', ts) AS \"time\",\n  d.alias,\n  SUM(energy_kwh) AS \"value\"\nFROM fact_energy_hourly as f\nJOIN generic_device as d ON d.id = f.device_id\nWHERE $__timeFilter(ts) and d.client = '$site_name'\nGROUP BY 1, 2\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Temperature & Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "ocei3",
     "rawSql": "SELECT \n\"timestamp\" AS \"time\", \ntemperature AS \"Temperature (°C)\", \nhumidity AS \"Humidity (%)\",\nsource_device_id\nFROM environmental_metrics as env \nJOIN generic_device as d on d.id = CAST(env.source_device_id as INT)\nwhere d.client = '$site_name'\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Hourly Consumption (kWh) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "ocei3",
     "rawSql": "SELECT\n  f.ts AS \"time\",\n  d.alias AS \"metric\",       -- Joins to the device table to get the human-readable name\n  f.energy_kwh AS \"hh\"\nFROM fact_energy_hourly f\nJOIN generic_device d ON f.device_id = d.id\nWHERE $__timeFilter(f.ts) and d.client = '$site_name'\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Daily consumption (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "ocei3",
     "rawSql": "SELECT\n  DATE_TRUNC('day', ts) AS \"time\",\n  d.alias,\n  SUM(energy_kwh) AS \"value\"\nFROM fact_energy_hourly as f\nJOIN generic_device as d ON d.id = f.device_id\nWHERE $__timeFilter(ts) and d.client = '$site_name'\nGROUP BY 1, 2\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Milk production (kg) & Fed (kg) per cow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "dataset": "ocei",
     "rawSql": "SELECT\n  production_date AS \"time\",\n  (day_production_per_cow_kg * number_of_animals) AS \"Production (kg)\",\n  (fed_per_cow_total_kg * number_of_animals) AS \"Food Consumption (kg)\"\n  -- (fed_per_cow_water_kg * number_of_animals) AS \"Water Consumption (kg)\"\nFROM dairy_production as prod\nJOIN generic_device as d ON d.id = CAST(prod.source_device_id AS INT)\nWHERE $__timeFilter(production_date) and d.client = '$site_name'\nORDER BY 1;"
    }
   ]
  }
 ]
}